#!/bin/sh
# bench/RESULTS.md を再生成する。事前に ./bench/corpus.sh (+ 各 corpus で kenning bake 推奨)。
# 使い方: ./bench/run.sh   (kenning は cargo install 済みの想定)
set -e
cd "$(dirname "$0")/.."
D="${KENNING_BENCH_DIR:-$HOME/.cache/kenning-bench}"
OUT=bench/RESULTS.md

{
    echo "# bench results"
    echo
    echo "Generated by \`./bench/run.sh\` ($(uname -s) $(uname -m)) / each table describes its own method and model right above it."
    echo "Corpora are pinned to tags (bench/corpus.sh). Random numbers use a fixed seed — the same environment gives the same numbers."
} > "$OUT"

for repo in "$D/tokio" "$D/ripgrep" ../enchudb .; do
    [ -d "$repo" ] || { echo "skip: $repo (missing — run ./bench/corpus.sh first)" >&2; continue; }
    name=$(basename "$(cd "$repo" && pwd)")
    echo >> "$OUT"
    echo "## corpus: $name" >> "$OUT"
    echo >> "$OUT"
    (cd "$repo" && kenning bench all) >> "$OUT"
done
# 環境の絶対パスを落とす (公開 repo に home dir を混ぜない)
sed -i '' "s|$HOME|~|g" "$OUT" 2>/dev/null || sed -i "s|$HOME|~|g" "$OUT"
echo "wrote $OUT" >&2
